### ISSUE TITLE
Adding Netlify CMS

### ISSUE THREAD

**Issue by rahuldotbiz** [adisaktijrs/hexo-theme-minima#10]
Netlify CMS is best thing for blogger instead of just commit and pushing they can simple use the /admin using the netlify CMS. Can you plz plz add to this amazing template.

**Comment by adisaktijrs** [comment]
Hi, I do sorry since I was currently busy with some offline projects therefore I can't promise to make those things sometime soon. Thank you for using this theme tho 😁
