### ISSUE TITLE
Can't see the blog title in homepage 

### ISSUE THREAD

**Issue by rahuldotbiz** [adisaktijrs/hexo-theme-minima#11]
Hey amazing developer, i can't see the title i homepage of this website having problem in it. 
Help me plz see the pics below no problem. I tried many ways to do it. 
<img width="543" alt="1" src="https://user-images.githubusercontent.com/62949229/100605472-f9a7ca00-332d-11eb-8523-51591e579149.png">
<img width="890" alt="2" src="https://user-images.githubusercontent.com/62949229/100605481-fdd3e780-332d-11eb-962a-01321710e914.png">
<img width="703" alt="Screenshot 2020-11-30 170246" src="https://user-images.githubusercontent.com/62949229/100605486-ff051480-332d-11eb-9773-fdd46d2223a1.png">

**Comment by adisaktijrs** [comment]
Hi, does it happen every time you tried to create new post? If it doesn't try to clean your Hexo cache with this command:
```
hexo clean
hexo server
```

Anyway thanks for using this theme!

**Comment by rahuldotbiz** [comment]
No i tried many possible ways to do that can't figured out.

**Comment by rahuldotbiz** [comment]
What i'll do is reinstall it and make it.

**Comment by rahuldotbiz** [comment]
I'm in love with this theme and also can you plzz push some features. Like mailchimp integration and a small search bar at top plzzz. I'm a professional blogger currently hunting for theme this is what currently i'm in love with. 

I currently blog at - https://blog.rahulism.co 


THANK YOU SO MUCH (waiting for your reply)

**Comment by rahuldotbiz** [comment]
I think this error will not go for me

**Comment by rahuldotbiz** [comment]
i tried with cloning once again and developing
Not succesfull

**Comment by adisaktijrs** [comment]
Glad to hear that you love this theme. Anyway I think those such features belongs to Hexo plugins. I found useful plugin for dealing with search bar like [this one](https://github.com/wzpan/hexo-generator-search) but yeah we still need to tweak the theme to add ajax/else to make a search bar. I do sorry since I was currently busy with offline project therefore I can't promise to make those things sometime soon.
Or if you wish, you can also contribute to this theme as well 😁

Anyway, your blog is great!

**Comment by adisaktijrs** [comment]
Does It always happened every time you creating new post?

**Comment by rahuldotbiz** [comment]
yea. 
Faced every time

**Comment by adisaktijrs** [comment]
Hi, I just tested both the development and the latest release v1.1 version of this theme. But I found no error, both work fine.
Does the problem affect other posts? Or just the first one?

**Comment by rahuldotbiz** [comment]
Just first one and all the new ones.

**Comment by rahuldotbiz** [comment]
I think you should work on your other projects as for this i am working on it right now and will surely find some other solution.


(WAITING TO SEE YOU NEXT BLOG TEMPLATE MAKE SOMETHING AMAZING)
