### ISSUE TITLE
Google Analytics support

### ISSUE THREAD

**Issue by conor10** [adisaktijrs/hexo-theme-minima#18]
Really like this theme, I have a few questions which I'll create as issues.

Is it possible to add a Google Analytics tag to the theme?

**Comment by adisaktijrs** [comment]
Hi @conor10, glad to hear that!

Yes it is. You can simply add these lines and your Tracking ID to this theme [config.yml file](https://github.com/adisaktijrs/hexo-theme-minima/blob/526ab645aa89a09ca0c146c053dae6d18782393c/_config.yml):
```markdown
# Google Analytics ID
google_analytics: # your Tracking ID goes here
```

Or you can manually add codes generated by Google Analytics to the head section of this theme on [layout.ejs file](https://github.com/adisaktijrs/hexo-theme-minima/blob/526ab645aa89a09ca0c146c053dae6d18782393c/layout/layout.ejs)

**Comment by conor10** [comment]
Awesome, thanks.
