### ISSUE TITLE
Customise footer

### ISSUE THREAD

**Issue by conor10** [adisaktijrs/hexo-theme-minima#19]
How can I customise the footer further? 

I'd like to be able to add a copyright and the current year, plus a link to my YouTube channel.

**Comment by adisaktijrs** [comment]
Hi, this theme uses [EJS](https://ejs.co/) to make the layout, so you may need to tweaks its [footer section](https://github.com/adisaktijrs/hexo-theme-minima/blob/526ab645aa89a09ca0c146c053dae6d18782393c/layout/partial/footer.ejs) file to customize it manually.

**Comment by conor10** [comment]
Great, thanks.
