### ISSUE TITLE
Footer icon incompatible

### ISSUE THREAD

**Issue by changliu98** [adisaktijrs/hexo-theme-minima#2]
Preview is directly from demo:
![image](https://user-images.githubusercontent.com/24647271/96821541-1cbd9080-13f6-11eb-91c2-3b52bfd1910f.png)
My guess for this is caused by
https://github.com/adisaktijrs/hexo-theme-minima/blob/15c3b0f2a8806dc1231a0131cc323fb536257057/source/css/skeleton.css#L295
Also, I can see there are plenty of hacks can be done within this theme, but usually they locates within skeleton.css, hope you can collect these customization and add options in config.yml
Good work!

**Comment by adisaktijrs** [comment]
Hi, yes you are right, the footer icons don't fit to the hover. And there are still a lot of customization that can be done with this theme. I will try to fix it for the next release. Thank you in advance, I will also wait for your PR if you wish 😁

**Comment by adisaktijrs** [comment]
Fixed at f96c7dda9e3cfbaad4df1575e01ac50b38f5b01a
