### ISSUE TITLE
List posts by tags

### ISSUE THREAD

**Issue by conor10** [adisaktijrs/hexo-theme-minima#20]
Is it possible to list posts by tags?

**Comment by adisaktijrs** [comment]
Hi, Minima has its default page for certain tags, for example [this page](https://adisaktijrs.github.io/minima/tags/Beauty/).

Or if you mean list all posts on a custom page, this answer [may help](https://stackoverflow.com/questions/38998718/how-to-filter-posts-by-tag-in-hexo).
