### ISSUE TITLE
some features hope to support.

### ISSUE THREAD

**Issue by opfanswyx** [adisaktijrs/hexo-theme-minima#23]
I like this theme very much, it is very concise, but there are some minor problems, I hope to get support . https://atticuslab.com

1. hope support latex
![image](https://user-images.githubusercontent.com/20237214/123200247-ea16eb00-d4e2-11eb-82cb-3a21accb7c20.png)

2. <table>tag will exceed the page width limit 
![image](https://user-images.githubusercontent.com/20237214/123200149-c81d6880-d4e2-11eb-9bef-bd52aa991a1a.png)

3. <code>tag hopes to have a significant effect 
![image](https://user-images.githubusercontent.com/20237214/123200273-f69b4380-d4e2-11eb-8389-24aae1367924.png)

**Comment by adisaktijrs** [comment]
Hi, thanks for using this theme.

Anyway, I do sorry, I couldn't help you to tweak this theme due to my offline business. But, for LaTeX support, you can use 3rd party plugin in Hexo to generate that, there are some of these plugins in the Hexo plugin page that you can try to use.

**Comment by opfanswyx** [comment]
Thanks, some problems have been solved.(
