### ISSUE TITLE
Pages Won't Load

### ISSUE THREAD

**Issue by elyserobinson** [adisaktijrs/hexo-theme-minima#27]
I'm trying to figure out why my pages are showing the source code instead of loading the .md file.

Also, what do I put to add pages to the config file? And where do I put those files? For example, the About page and file. That won't load either.

Here is an example I created: https://dreamy-darwin-5a2f0b.netlify.app/

**Comment by adisaktijrs** [comment]
Hi there! I haven't faced this kind of problem before. Have you tried to create a new post to just check if this problem is unique to that post or not?

Anyway, for pages and files you can try this tutorial:
https://www.youtube.com/watch?v=AIqBubK6ZLc&list=PLLAZ4kZ9dFpOMJR6D25ishrSedvsguVSm

**Comment by elyserobinson** [comment]
I figured out how to do pages. Still running into the problem with the posts though. Thank you for a quick response!!!!

**Comment by elyserobinson** [comment]
Ok figured out the posts...

permalink: :title/

instead of what I had

permalink: :title
