### ISSUE TITLE
New feature request: add a search feature

### ISSUE THREAD

**Issue by aJIEw** [adisaktijrs/hexo-theme-minima#30]
Hi, thanks for creating this great theme, I love it. And I'm wondering if you are considering adding a search feature, like [local search](https://theme-next.js.org/docs/third-party-services/search-services.html#Local-Search) or something similar?

**Comment by jinzhongjia** [comment]
Maybe you can take a look at this plugin [hexo-generator-search](https://github.com/wzpan/hexo-generator-search)

Incidentally, I may be able to complete this function in the future🤔

**Comment by jinzhongjia** [comment]
i have add a search feature (local search) through this  [Repositories](https://github.com/wzpan/hexo-generator-search),however,I found as like as two peas of Repositories.
and i have pull requests😃
After it uploads the locally generated JSON file to the server, JS applies for and parses it to achieve the purpose of search, but I only configure the function of searching the article title

**Comment by adisaktijrs** [comment]
Hi, this feature is already being implemented by @yingyi666!
Here's his PR #33 if you wanna check how to use the search feature. I'll update the documentation to reflect this update soon.
