### ISSUE TITLE
work well with “hexo s”, but work bad on github.

### ISSUE THREAD

**Issue by RuoyiDu** [adisaktijrs/hexo-theme-minima#35]
When I push the theme to my github repository, it seems is not correctly compiled.

**Comment by adisaktijrs** [comment]
Hi, can you provide me some screenshoot of your browser console when running minima on github pages?

Or you can try the stable release 2.0 [here](https://github.com/adisaktijrs/hexo-theme-minima/releases/tag/v2.0) to see if this problem caused by the development version of it.

**Comment by RuoyiDu** [comment]
<img width="480" alt="1644949964(1)" src="https://user-images.githubusercontent.com/61931443/154206412-4c12a860-f274-44f7-a34b-b912e1bdbc37.png">

**Comment by jinzhongjia** [comment]
> <img width="480" alt="1644949964(1)" src="https://user-images.githubusercontent.com/61931443/154206412-4c12a860-f274-44f7-a34b-b912e1bdbc37.png">
> 

em....
Obviously, your css file is not working properly
check css files🤔

**Comment by RuoyiDu** [comment]
> 
But it does work well on the localhost. So I think the CSS file is correct. Could some configuration mistakes of my github repository cause this?

**Comment by jinzhongjia** [comment]
> > 
> 
> But it does work well on the localhost. So I think the CSS file is correct. Could some configuration mistakes of my github repository cause this?

sorry,i can't help more,i haven't used github page👀

**Comment by RuoyiDu** [comment]
> > > 
> > 
> > 
> > But it does work well on the localhost. So I think the CSS file is correct. Could some configuration mistakes of my github repository cause this?
> 
> sorry,i can't help more,i haven't used github page👀

Okay, still thanks a lot!

**Comment by bosswnx** [comment]
> > > > 
> > > 
> > > 
> > > But it does work well on the localhost. So I think the CSS file is correct. Could some configuration mistakes of my github repository cause this?
> > 
> > 
> > sorry,i can't help more,i haven't used github page👀
> 
> Okay, still thanks a lot!

Hi! I met this problem too. I wonder whether you solve it? Thanks!

**Comment by jinzhongjia** [comment]
> > > > > 
> > > > 
> > > > 
> > > > But it does work well on the localhost. So I think the CSS file is correct. Could some configuration mistakes of my github repository cause this?
> > > 
> > > 
> > > sorry,i can't help more,i haven't used github page👀
> > 
> > 
> > Okay, still thanks a lot!
> 
> Hi! I met this problem too. I wonder whether you solve it? Thanks!

You can open your browser's developer tool, and check the info printed by console
in general, it is caused by css loading error.

**Comment by bosswnx** [comment]
已收到，谢谢。
